### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by josa42** [feinkost-internet/feinkost-internet.github.io#1]
Last uns mal ein bisschen für eine Logo brainstormen.

**Comment by josa42** [comment]
![feinkost-internet](https://user-images.githubusercontent.com/423234/31221649-9ff95b18-a9c4-11e7-8d0d-0eafd7c3a87f.png)

**Comment by josa42** [comment]
![feinkost-internet-mouse-and-keyboard](https://user-images.githubusercontent.com/423234/31233496-1a07e3ca-a9ed-11e7-9358-ebf4790fd62f.png)

**Comment by developdude** [comment]
<img width="309" alt="screen shot 2017-10-05 at 13 45 17" src="https://user-images.githubusercontent.com/10866968/31233610-5a1a9746-a9ed-11e7-97ba-ee0e56e7bc76.png">

Gefällt mir irgendwie auch.

**Comment by josa42** [comment]
@developdude Das löst irgendwie Panik in mir aus :-D
