### ISSUE TITLE
Texte

### ISSUE THREAD

**Issue by developdude** [feinkost-internet/feinkost-internet.github.io#4]
- Subline
- Impressum
- Hello World Post

**Comment by developdude** [comment]
# Subline Vorschläge
Feinkost Internet
- … Der Schminktipp fürs Gehirn
- Der Podcast von dem Sie nicht wollen das Du ihn hörst!1
- Saftiges Internet zu feinem Podcast handeingesprochen
- Letzte Feinkost vor dem Internet
- Vor dem Darknet gleich links

**Comment by josa42** [comment]
Folgende Texte fehlen noch für den Feed:

```
podcast_description: "Lorem Ipsum"
podcast_summary: "Lorem Ipsum"
```

So bei description und summary das gleiche zu sein scheint

> Take advantage of the <itunes:summary> tag. The <itunes:summary> tag (or the <description> tag if <itunes:summary> isn’t present) allows you to inform users about your podcast. Describe your subject matter, media format, episode schedule, and other relevant information. Apple Podcasts removes podcasts that include irrelevant words in the <itunes:summary> or <description> tags.

Quelle: https://help.apple.com/itc/podcasts_connect/#/itc2b3780e76

Sollen wir da den text von der Über uns Seite nehmen?

> Gegründet 2017 im Süden von Deutschland wurde der Traditionsbetrieb über Nacht der Geheimtipp für frisches Internet. Bei Feinkost Internet steht seit jeher die Liebe zum Internet im Vordergrund der Traditionsmanufaktur. Noch heute kommen die Gründer zusammen, sprechen ihren Podcast von Hand ein und tragen persönlich Sorge dafür das aus aktueller Technologie, deinem Spamfolder und dem neuen Film von Til Schweiger saftiges Internet wird.

**Comment by josa42** [comment]
FYI ich wähle jetzt einfach "Letzte Feinkost vor dem Internet" als Subline, liegt mir irgendwie am nächsten.
