### ISSUE TITLE
Twitter Handle

### ISSUE THREAD

**Issue by developdude** [feinkost-internet/feinkost-internet.github.io#5]
Wir brauchen einen catchy Twitter Handle

**Comment by developdude** [comment]
# Requirements
- 15 chars (feinkostinterne**t**)
- akustisch gut verständlich

# Vorschläge
- leckerfeinkost
- leckerinternet
- fkinternet
- feinkostinc
- feinkostwap
- feinkostheftcd

and als bonus on top: f1nkostinternet, vong Name her.

**Comment by josa42** [comment]
Gegenvorschlag: `internetkost`.

**Comment by t-sauer** [comment]
Ich hät noch feinkostonline zu bieten.

**Comment by Huberst** [comment]
Feinkostnet ?

**Comment by josa42** [comment]
[@internetkost](https://twitter.com/internetkost)!
