### ISSUE TITLE
Podcast kategorien

### ISSUE THREAD

**Issue by josa42** [feinkost-internet/feinkost-internet.github.io#8]
Wir müssen uns noch für eine Podcast-Kategorie entscheiden, die im Feed angegeben wird.

> Be sure to include a valid <itunes:category> tag. You can also define a subcategory if one is available. Podcasts with category information appear in more places in Apple Podcasts and are more likely to be found by users. Your category should be in English in the XML of your feed, but is localized in Apple Podcasts.

AFAIK können auch meherer Kategorien angeben.

**Comment by josa42** [comment]
Die Kategorien sind:

- Arts:
  - Design
  - Fashion & Beauty
  - Food
  - Literature
  - Performing Arts
  - Visual Arts
- Business:
  - Business News
  - Careers
  - Investing
  - Management & Marketing
  - Shopping
- Comedy
- Education:
  - Educational Technology
  - Higher Education
  - K-12
  - Language Courses
  - Training
- Games & Hobbies:
  - Automotive
  - Aviation
  - Hobbies
  - Other Games
  - Video Games
- Government & Organizations:
  - Local
  - National
  - Non-Profit
  - Regional –
- Health:
  - Alternative Health
  - Fitness & Nutrition
  - Self-Help
  - Sexuality
  - Kids & Family
- Music
- News & Politics:
  - Religion & Spirituality:
    - Buddhism
    - Christianity
    - Hinduism
    - Islam
    - Judaism
    - Other
    - Spirituality
- Science & Medicine:
  - Medicine
  - Natural Sciences
  - Social Sciences
- Society & Culture:
  - History
  - Personal Journals
  - Philosophy
  - Places & Travel
- Sports & Recreation:
  - Amateur
  - College & High School
  - Outdoor
  - Professional
  - TV & Film
- Technology:
  - Gadgets
  - Podcasting
  - Software How-To
  - Tech News

**Comment by developdude** [comment]
- Tech
  - Podcasting

Mehr trifft nicht zu.

**Comment by Huberst** [comment]
Meiner Meinung nach Comedy schon auch.

**Comment by josa42** [comment]
> * Tech
>     * Podcasting

Mach aus meiner Sicht keinen Sinn, weil wir nicht über Podcasten podcasten.

Ich nehme jetzt mal:

* Commedy
* Technology
    * Tech News

Wir können das ja auch noch mal ändern.
